### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a3@gmail.com",
    "password": "asdf"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/12

### Find all users with a given Email
GET http://localhost:3000/auth

### Delete a user with a given ID
DELETE http://localhost:3000/auth/6

### Update a user with a given ID
PATCH http://localhost:3000/auth/12
Content-Type: application/json

{
    "email": "TT4@gmail.com",
    "password": "qwerT4"
}